{% set name = "rope" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 366789e069a267296889b2ee7631f9278173b5e7d468f2ea08abe26069a52aef

build:
  number: 0
  skip: True # [py<36]
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools

  run:
    - python >=3.6

test:
  imports:
    - rope
    - rope.base
    - rope.base.oi
    - rope.base.oi.type_hinting
    - rope.base.oi.type_hinting.providers
    - rope.base.oi.type_hinting.resolvers
    - rope.base.utils
    - rope.contrib
    - rope.refactor
    - rope.refactor.importutils
  requires:
    - pip
    - python <3.10
  commands:
    - pip check

about:
  home: https://github.com/python-rope/rope
  license_file: COPYING
  license: LGPL 3.0-or-later
  license_family: LGPL
  summary: A python refactoring library
  dev_url: https://github.com/python-rope/rope
  doc_url: https://pypi.python.org/pypi/rope
  doc_source_url: https://github.com/python-rope/rope/tree/master/docs

extra:
  recipe-maintainers:
    - pmlandwehr
    - jjhelmus
