{% set name = "rope" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5c5a6a87f7b1a2095fb311135e2a3d1f194f5ecb96900fdd0a9100881f48aaf

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - rope
    - rope.base
    - rope.base.oi
    - rope.base.oi.type_hinting
    - rope.base.oi.type_hinting.providers
    - rope.base.oi.type_hinting.resolvers
    - rope.base.utils
    - rope.contrib
    - rope.refactor
    - rope.refactor.importutils

about:
  home: https://github.com/python-rope/rope
  license_file: COPYING
  license: GPL 2.0
  summary: 'A python refactoring library'
  dev_url: https://github.com/python-rope/rope
  doc_url: https://pypi.python.org/pypi/rope
  doc_source_url: https://github.com/python-rope/rope/tree/master/docs

extra:
  recipe-maintainers:
    - pmlandwehr
    - jjhelmus
