{% set name = "rope" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba39581d0f8dee4ae8b5b5e82e35d03cebad965ccb127b7eaab9755cdc85e85a

build:
  number: 0
  skip: True # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - pytoolconfig >=1.2.2

test:
  imports:
    - rope
    - rope.base
    - rope.base.oi
    - rope.base.oi.type_hinting
    - rope.base.oi.type_hinting.providers
    - rope.base.oi.type_hinting.resolvers
    - rope.base.utils
    - rope.contrib
    - rope.contrib.autoimport
    - rope.refactor
    - rope.refactor.importutils
  requires:
    - pip
    - pytest
  source_files:
    - ropetest
  commands:
    - pip list
    - pip check

about:
  home: https://github.com/python-rope/rope
  license_file: COPYING
  license: LGPL-3.0-or-later
  license_family: LGPL
  summary: A python refactoring library
  description: |
    Rope is the world's most advanced open source Python refactoring library (yes, I totally stole that tagline from Postgres).
  dev_url: https://github.com/python-rope/rope
  doc_url: https://rope.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jjhelmus
