travis:
  secure:
    BINSTAR_TOKEN: yCplZelA5eLQZKRd2L7CK24PWXE8AZD+SxkQhUo5CaMWPppJps/492G127DGEvRyll9gjr0+XpuzK7yxdg2uPzX8ehlh589PXpSBjWEywwdMp1exAV0fGeNOiri+5RCQDejfZsqNog0dgZW0FrTkXiZiTpKsnb4KgY3BzVk+0XVaKSdFnZwKpuP7MeJ6mcU33OFZFrmv7AcnhJhVotBvnv5dMXtn/9LsibcXNTEIFLgs6AJB7rXgxfnOPXy68fFxLfeYetkYVFpnxQn0BTSInQVZ8HHRXamWKNxnMWZKJn15rpkL89xwgY9kbbd3jXcKnBlCa9AedjR6EG79Joc1lHgJK2tJGCyqi4ZW1Nxv0TQV6bDRPVkzXtTwXc1i0MlHrMhjl3WkYXwDhQm1vpicGScJZ/6E4qLUurgtWTAXvi4HFvDu/G/15Rrt5ZACthh2ukMzJsKyRspeq9NnK//Z3VkVp4RGtaQKN5eHH60AQagVdlV8n1lscG2NCWm/3Mxs3Af7tyGipO1qX3shRHYlyYOq8XrlYXDTYkOPDqHgbBRlbRWUW/bBFzME5cUa3RqNvSfuP9MzwcN1fO7ExBB0qtHUHOa1xH+83vU7dNPj8iZxUO17djfniFkPB90vQsZUIZOxvlOZjYHQ88MSBda4QvsB9V7/1g+BqxpZ7fLow4A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
