travis:
  secure:
    BINSTAR_TOKEN: HLCrCnPYjo4YvC5N3YcJHnf+HnA8il/AA+KN+2zDRGs7oWxaXlgLietQq1i4Ds3WsKoLrnSTO8bXr7N8uAhGHhoCO3+nveHbBXPxrWe9ps2MGftu8MUji87l/p25o2hTzUbIuomrBgcKVHUCkGi5kVWzNAaubYzlJXZu+bIl+Y1/Q4uPvmY//wTahTGEDyPWlX8gvz+hHGtUBMJ0BGe6lX3bojWtH3KN191+Ulax8LkqQpokZDBWIGkIEwV0/hCWIrsfU/BUlS++T5R+38J0jv7G2ykREnybywEmMl7Efp2wtxpYqib5IMe/g9H4lCJOFB9wn8uE/IzSk93EdAgm8Dmtfd5fp0Q95dxFQLRiEXJIhCvvuXsOIfM+A7uXcQuEx7nRzc+OML7NnNeJWwYyoVuJqLpPof0J4/NBOJMTSdCJXtjjANBAn2BM2+v8TmR1SVq6Mwqy2u2qThvehuU+eE0C8AFS7ukPrag78oZEJrxgKvFMSN06cs6qvQ7qypoxr3/gi4MMzS7pA4IExPzjkl0q/T4B1UNXMTtJIhMgtyWgEBvpY/6kINtZ8gWQ0cj9CW+vchRvJJyNqFqm4sdZrAexOyOj7ToZC3zqnSYFCmw+vLRiDxLKaTnrc9WTzA9MfWpb0iZPzZgNfb/BpkuvsOHtehyonMe1pnErTqtg1wo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
